### PR TITLE
Add network bootstrap example

### PR DESCRIPTION
**Pull request by gohdan**
Bootstrap example is suitable only to localhost, there is need to show how to bootstrap remote machine.

### CODE REVIEW

**Comment by casperr0** [comment]
thank you for your interest in the project! 
the ability to monitor PG on another machine using bootstap should be added to readme as you proposed. but you don't have to give mamonsu user superuser rights even temporarily to do so. 
try :
bootstrap -M mamonsu  --host=postgresql_host
here mamonsu is name of non-privileged user
for bootstrap -U option is for database superuser name(default is 'postgres'). which is in your example in the readme is 'mamonsu' the same as non-privileged (-M option) user. that's why in your example user 'mamonsu' have to get superuser rights before bootstap command

**Comment by gohdan** [comment]
Thank you for your reply. But as I recently discovered, mamonsu need superuser rights to work with database even after bootstrap because superuser rights are required to execute functions like pg_ls_dir.

**Comment by casperr0** [comment]
the way bootstap works is that as superuser it creates functions (for example  public.mamonsu_archive_command_files() ) which return the information you need,  grand execution rights to this functions to the non-privileged user ('mamonsu' in my example)
check existing privileges to bootstap functions ( all names of bootstrap functions starts with 'mamonsu' ). use \df+  in psql to view info about functions.  does your bootstap functions were created by a user with superuser rights and does non-privileged user ( -M option)  has execution rights to them.

**Comment by gohdan** [comment]
Thank you for detailed explanation! I will close the pull request now and prepare new one, more accurate and considering your comments.

**Comment by casperr0** [comment]
glad that I could help!

**Pull request closed without merging**
